# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Build Kernel
      uses: dabao1955/kernel_build_action@main
      with:
          kernel-url: https://github.com/TC999/android_kernel_mediatek_mt6739
          kernel-dir: N107-6739
          kernel-branch: android-7.1
          config: defconfig
          arch: arm64
          aosp-gcc: true
          aosp-clang: true
          android-version: 10
          aosp-clang-version: 10
          disable-lto: true
          anykernel3: true
